In [ ]:
# GPU is faster for Deep Learning
print("Hello I'm excited to learn PyTorch!")


Hello I'm excited to learn PyTorch!


In [ ]:
!nvidia-smi

Mon Apr 17 01:30:59 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

###00.PyTorch Fundamentals

Resource notebok: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


*이탤릭체 텍스트*## Introduction of Tensors
### Creating Tensors

Pytorch tensors are created using 'torch.Tensor()' -= https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # Alias for dim(), scalar has 0 dim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 5]])

In [ ]:
# Note the scalars and vectors are lowercase while matrix and tensor uppercase

### Random tensors

Why random tensors? 

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data. 

'start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1032, 0.1326, 0.4441, 0.1005],
        [0.3287, 0.2940, 0.1773, 0.9509],
        [0.7699, 0.2087, 0.8153, 0.4912]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor = torch.rand(10,10)
random_tensor

tensor([[0.9344, 0.4641, 0.8509, 0.4780, 0.8848, 0.4572, 0.8107, 0.8400, 0.9215,
         0.7417],
        [0.1657, 0.4763, 0.1197, 0.4072, 0.3708, 0.0259, 0.9493, 0.9208, 0.9469,
         0.7110],
        [0.4775, 0.7068, 0.7013, 0.2744, 0.5613, 0.8457, 0.6272, 0.6401, 0.5116,
         0.8419],
        [0.3827, 0.7888, 0.9442, 0.8198, 0.9004, 0.8825, 0.7130, 0.1530, 0.6340,
         0.8880],
        [0.1671, 0.6765, 0.9045, 0.7791, 0.7341, 0.6603, 0.0319, 0.2302, 0.2522,
         0.4487],
        [0.5400, 0.4251, 0.3785, 0.7656, 0.6231, 0.3845, 0.0227, 0.2766, 0.5681,
         0.5244],
        [0.8013, 0.7984, 0.6941, 0.8264, 0.6983, 0.9008, 0.6340, 0.7763, 0.0151,
         0.0877],
        [0.0599, 0.6669, 0.0057, 0.8032, 0.7465, 0.2614, 0.0585, 0.3061, 0.1075,
         0.8808],
        [0.3737, 0.5431, 0.0881, 0.7068, 0.6465, 0.4797, 0.2815, 0.8955, 0.3251,
         0.0621],
        [0.4531, 0.4729, 0.9152, 0.8983, 0.7330, 0.8233, 0.2287, 0.3398, 0.0134,
         0.6245]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(3, 3)
# torch.rand(size=(3,3))

tensor([[0.9969, 0.6049, 0.6884],
        [0.3478, 0.6468, 0.9992],
        [0.4266, 0.6399, 0.8340]])

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))

In [ ]:
ones.dtype # default data type

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor.dtype
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], # what datatype is the tensor (e.g. float32 or float 16)
                               dtype=None,
                               device=None, # what device is your tensor on /// by degault for now = CPU, could change to "cuda"... If not in same device -> pytorch error!
                               requires_grad=False) # whether or not to track gradients with this tensors operations
                               
float_32_tensor

tensor([3., 6., 9.])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors (issues) with PyTorch & deep learning)
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Note. Precision in Computing

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6446, 0.7866, 0.7677, 0.7308],
        [0.4955, 0.1574, 0.7383, 0.4450],
        [0.9225, 0.9556, 0.9405, 0.9262]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.6446, 0.7866, 0.7677, 0.7308],
        [0.4955, 0.1574, 0.7383, 0.4450],
        [0.9225, 0.9556, 0.9405, 0.9262]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [ ]:
# Subtract 10
tensor - 10

tensor([100, 110, 120])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([1100, 1200, 1300])

In [ ]:
torch.add(tensor, 10)

tensor([120, 130, 140])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplixation needs to satisfy:
1. The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work (@ is matrix multiplication)
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work

2. The resulting matrix has the shape of the **outer dimensions**:
* '(2,3 @ (3,2)' --> (2,2)
* '(3,2) @ (2, 3)' --> (3,3)

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([110, 120, 130]) * tensor([110, 120, 130])
Equals: tensor([12100, 14400, 16900])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(43400)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(43400)
CPU times: user 399 µs, sys: 0 ns, total: 399 µs
Wall time: 423 µs


In [ ]:
%%time
torch.matmul(tensor, tensor) # 10 times faster!!! - vectorization rather than doing for loop

CPU times: user 46 µs, sys: 0 ns, total: 46 µs
Wall time: 49.4 µs


tensor(43400)

### One of the most common errors in deep learning: shape Errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2], [3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**.

A **transpose** switches the axes or dimensions of a given tensor. 

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}") # torch.matmul(tensor_A, tensor_B.T).shape


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Finmd the mean
mean_x1 = torch.mean(x.type(torch.float32))
mean_x2 = x.type(torch.float32).mean()


In [ ]:
mean_x1, mean_x2

(tensor(46.), tensor(46.))

In [ ]:
# Find Sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the Positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() --> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor thaqt has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a dewfined shape
* View - Return a view of an input tensor of sertain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - REturn a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
# x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9) # shares the same membery with x
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory of the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor

x = torch.zeros(2, 1, 2, 1, 2)
x.size()
y = torch.squeeze(x)
y.size()
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()
y = torch.squeeze(x, (1, 2, 3))

In [ ]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels] # typical image data

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 ->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}") # [colour_channels, height, width]
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 91734
x_original[0, 0, 0], x_permuted[0, 0 ,0] # same memory

(tensor(91734.), tensor(91734.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)

In [ ]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# You can also use ':' to select "all" of a target dimension
x[:, 0]
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor. -> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy -> 'torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # When converting pytorch from numpy, -> pytorch, pytorch reflexts numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 9.0).dtype

torch.float32

In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tesor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor # means: they don't share memory

(tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

'start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...'

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "Flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5956, 0.6564, 0.7650, 0.6374],
        [0.6580, 0.6962, 0.5629, 0.7883],
        [0.8647, 0.5507, 0.4904, 0.6507]])
tensor([[0.2781, 0.9031, 0.1941, 0.7946],
        [0.2443, 0.1380, 0.5467, 0.0312],
        [0.5578, 0.9234, 0.1688, 0.6132]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
1 == 1

True

In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
# torch.manual_seed(RANDOM_SEED)

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### EXTRA resource for reproducibility

https://pytorch.org/docs/stable/notes/randomness.html

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardward + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU
1. Easiest - Use Google colab / pro ($9.99  month)
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure, - allow you to rent computers on the cloud and access them.


In [ ]:
!nvidia-smi

Mon Apr 17 02:24:13 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

In [ ]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device) # ***important
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU 

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy() # works as it's put back to cpu before using Numpy
tensor_back_on_cpu 

array([1, 2, 3])